### PR TITLE
Fix CI bug that prevents non-forked branches from being pushed

### PR DESCRIPTION
**Pull request by dbirks**
Addresses #115

I started adding another condition to that `if` statement, but noticed it would be less complex to set `PUSH_IMAGE` to true by default, and only make it false if the PR head is not `ContainerSolutions/externalsecret-operator`. How does that sound?

### CODE REVIEW

**Comment by knelasevero** [comment]
I am not sure, but I think that github.event.pull_request and all nested values won't exist when CI runs for something not coming from a Pull Request.

**Comment by dbirks** [comment]
Oh you're right, then `''` will not equal `ContainerSolutions/externalsecret-operator`, and it won't push the image.
I'll go back and look at your original comment...

**Comment by dbirks** [comment]
Ok, I think this now covers everything;
- if a normal commit or merge to master, then push.
- if an internal PR to master, then push.
- if it's both a PR, and a fork, then don't push.

**Comment by dbirks** [comment]
Ah, it looks like the checks are failing because `github.event` is an object, and doesn't equal `pull_request`. Looks like `github.event_name` is what I want. Trying that...

**Comment by knelasevero** [comment]
Nice! Let's see with it merging now :)

**Review by knelasevero — APPROVED** [review]

**Pull request merged**
