### PR TITLE
Include our op module fork

### PR DESCRIPTION
**Pull request by knelasevero**
We had to create a fork of the 1password wrapper module to adapt it to work with new versions of op cli. This PR adds the fork as a dependency instead of the original one.

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
Hey mate, thanks for the PR!

We can also update the `ONEPASSWORD_CLI_VERSION` to `v1.8.0` on the `Dockerfile`

**Comment by knelasevero** [comment]
> Hey mate, thanks for the PR!
> 
> We can also update the `ONEPASSWORD_CLI_VERSION` to `v1.8.0` on the `Dockerfile`

That's true!

**Pull request merged**
